app_name: monorepo
env: development

database:
  host: localhost
  port: "5432"
  user: postgres
  password: postgres
  name: database

oauth_github:
  client_id: "client_id"
  client_secret: "client_secret"
  redirect_uri: "http://localhost:8081/api/v1/users/callback/github"

server:
  port: "8081"
  shutdown_timeout: 10
