basePath: /api/v1
info:
  contact: {}
  description: Saas API is a REST API for the Saas application.
  title: Saas API
  version: 1.0.0
paths: {}
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
